export const SUPPORTED_LANGUAGES = [
  { name: "English", value: "english" },
  { name: "Spanish", value: "spanish" },
  { name: "French", value: "french" },
  { name: "German", value: "german" },
  { name: "Polish", value: "polish" },
  { name: "Italian", value: "italian" },
  { name: "Portuguese", value: "portuguese" },
  { name: "Russian", value: "russian" },
  { name: "Japanese", value: "japanese" },
  { name: "Korean", value: "korean" },
  { name: "Mandarin Chinese", value: "mandarin" },
  { name: "Arabic", value: "arabic" },
  { name: "Hindi", value: "hindi" },
];
